# This is a basic workflow that is manually triggered
name: Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: 
    # Inputs the workflow accepts.
    inputs: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testjs:
    runs-on: node
    steps:
    - name: Test js
      run: node src/fourlines.full.js
